//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::article::Entity as Article;
pub use super::article_tag::Entity as ArticleTag;
pub use super::category::Entity as Category;
pub use super::tag::Entity as Tag;
