server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    absolute_redirect off;

    location = /feed.xml {
        types { }
        default_type application/atom+xml;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
