name: Cargo Test

on:
  pull_request:
    branches:
      - "master"
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"
      - ".env"
      - "Rocket.toml"
      - "blog_config.toml"
      - ".cargo/**"
      - "rust-toolchain*"
      - ".github/workflows/cargo_test.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install linker dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang mold

      - name: Cache Cargo
        uses: actions-rust-lang/setup-rust-toolchain@v2

      - name: Run test
        run: cargo test --workspace
